twitter:
  keys:
    consumerKey: 'RLSrphihyR4G2UxvA0XBkLAdl'
    consumerSecret: 'FTz2KcP1y3pcLw0XXMX5Jy3GTobqUweITIFy4QefullmpPnKm4'

server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:SYTEC;MODE=ORACLE
    username: sa
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
        properties:
          hibernate:
            format_sql: true
    h2:
      console:
        enabled: true
  application:
    name: sytac.io
logging:
  file:
    path: logFolder
